### ISSUE TITLE
Use nonce share from all participants for generating channelID.

### ISSUE THREAD

**Issue by manoranjith** [hyperledger-labs/perun-node#101]
#### Motivation / Context

A feature to use nonce share from all participants generating channel ID was added in go-perun in this [commit](https://github.com/perun-network/go-perun/commit/ba500c4ec66481043dfd0b89be170023ef7fa11a).

#### Description

Update perun node to use this feature. Similar to setting a nonce in channel proposal, it should also be set when accepting a new channel proposal.
This should not change anything for the user API. 

##### Relates to
Depends on https://github.com/hyperledger-labs/perun-node/issues/105

#### Testing

All existing tests should pass.

#### Thread Safety

Not required.

**Comment by anagha-ks** [comment]
Go-perun's [depositor  commit](https://github.com/hyperledger-labs/go-perun/commit/4bede739a3e4ce208390203ddd75aa3e2eb968b3) is between the previous [keystore](https://github.com/hyperledger-labs/perun-node/issues/105) change and this one. So first update Perun-node to include the [depositor](https://github.com/hyperledger-labs/go-perun/commit/4bede739a3e4ce208390203ddd75aa3e2eb968b3) feature and then apply this change.
