### ISSUE TITLE
Use uniform data formats in payment API.

### ISSUE THREAD

**Issue by manoranjith** [hyperledger-labs/perun-node#108]
#### Motivation / Context

Currently, different methods in the User API use different data structures. Eg: `Payment Channel` is used in return of [`Open Payment Channel`](https://github.com/hyperledger-labs/perun-proposals/blob/master/design/001-RPC-Interface-Specification.md#3-open-payment-channel) method and `Balance`, `Version` are used in [`Payment Channel Update Notification`](https://github.com/hyperledger-labs/perun-proposals/blob/master/design/001-RPC-Interface-Specification.md#2-subscribe-to-payment-channel-updates). However, `Payment Channel` can be used in latter case as well, as it contains `Balance`, `Version` along with `Channel ID`.

Identify such conditions and update to API specification to ensure data formats are used consistently across different methods in the API.      

#### Description

- [x] Update the API specification.
- [ ] Update the [`session API`](https://github.com/hyperledger-labs/perun-node/blob/ac0aefc75c5b10cca37842486c15fbc314be6454/session/session.go#L55), [`channel API`](https://github.com/hyperledger-labs/perun-node/blob/ac0aefc75c5b10cca37842486c15fbc314be6454/session/channel.go#L39) and the corresponding methods in [`payment`](https://github.com/hyperledger-labs/perun-node/tree/develop/app/payment) and [`grpc`](https://github.com/hyperledger-labs/perun-node/tree/develop/api/grpc) packages.

**Comment by manoranjith** [comment]
The changes proposed in [this update](https://github.com/hyperledger-labs/perun-proposals/commit/a0e2a6f9295a408c9ee16b7305ad79677ebd28d8) to perun-proposal #1, will implemented in a series of PRs (as listed below), each of which can be squashed to a single commit before merging:
- [ ] Use the following abbreviations for variable, func names with approrpriate prefix consistently: `Bal` for `Balance`, `BalInfo` for `BalanceInfo`, `Ch` for `Channel`, `ChInfo` for `ChannelInfo`, `PayCh` for `PaymentChannel`. With the following prefixes: `opening`, `opened`, `open`, `updated`, `closed` as necessary.
- [ ] Update `ChInfo` data type for uniform data format changes.
- [ ] Update OpenCh API for uniform data format changes. Also includes changes to `BalInfo` data format.
- [ ] Update `GetBalInfo` APIs for uniform data format changes.
- [ ] Update `RespondChProposal` APIs for uniform data format changes.
- [ ] Update `SendPayChUpdate`, APIs for uniform data format changes.
- [ ] Update `ChCloseNotif` data type for uniform data format changes.

**Comment by anagha-ks** [comment]
All the changes described in the [commit](https://github.com/hyperledger-labs/perun-proposals/commit/338f3096a83b7f323140fba1fc749b0d377dae05) in proposal repo is covered in these PRs, #112, #113, #115, #116.
