### ISSUE TITLE
Implement Session Close

### ISSUE THREAD

**Issue by manoranjith** [hyperledger-labs/perun-node#111]
#### Motivation / Context

To implement the session close function with proper handling of channels in different phases of their lifecycle.

#### Description

Currently, [session close](https://github.com/hyperledger-labs/perun-node/blob/c2451fc5f30d065f02b6c5f66e61ab34f6f37846/session/session.go#L514) is a No-op. Implement a session close mechanism with the following behavior:
1. When `force=true`, channels in all phases are locked, `channelClient` is closed and return a list of channels that are in open phase.
2. When `force=false`,
   - If there are channels in open phase, return an error with the list of channels in open phase.
   - If there are not channels in open phase, lock all the closed channels, close the `channelClient`.

#### Testing

1. Ensure channels in all phases of their lifecycle are handled properly.

#### Thread Safety

1. The `session.Close` should ensure the ongoing operations in any channel belonging to this session is completed.
2. The `session.Close` should ensure the ongoing operations in `statemachine` of `go-perun/channel` that was not initiated by `perun-node` is also completed. Currently only one such events exist: Watcher handling a registered event.

**Comment by manoranjith** [comment]
![image](https://user-images.githubusercontent.com/16356179/94410263-cc576800-0194-11eb-80d7-e9c01068173c.png)

The above image shows the state transition diagram for channel state machine in go-perun. From the `perun-node` point of view, each channel should be in one of the two phases: `Acting` or `Withdrawn`, when there is no ongoing operation on that channel. Channels in `Acting` phase are considered `Open` and those in `Withdrawn` phase are considered closed.

When closing a session,
1. For each channel, wait for any ongoing channel operation to complete by acquiring the channel mutex.
2. Collect the list of open channels. If the list is not nil, either return an error or close the session depending upon the value of `force` variable. In case, an error is returned, all the channels should be unlocked, as the session is still open and user must be able to access the channels.
3. Moreover, to ensure any register operation triggered in the `Watch` routine, read the `Phase` of the channel. Since `Phase()` function needs to lock on the mutex of the `statemachine`, it will ensure ongoing operation by channel is completed.

**Comment by manoranjith** [comment]
@sebastianst @ggwpez @RmbRT  I drew this state diagram based on the current version of go-perun on dev branch. Can you have a look and let me know if I have missed something ?

I think one difference from `go-perun` and `perun-node` points of view in the diagram is that
  - From `go-perun` POV, `Final` is also treated as a stable phase.
  - But, from `perun-node` POV, `Final` is a transition phase, because the `perun-node` software will call settle automatically on a channel in `Final` phase.

**Comment by sebastianst** [comment]
LGTM. I also think your handling of the `Final` phase as a _transition_ phase makes sense in your particular application, for now. From the SDK's pov, we don't want to force a user to immediately settle a final channel. There may be reasons why a channel should be settled later, e.g., the device is not connected to the internet or gas costs are currently high, or settle transactions are batched, etc.

**Comment by manoranjith** [comment]
Yeah, I agree that from the framework point of you, `Final` is treated as a stable phase and leave it upto the user of the `go-perun` framework to decide when to settle a finalized channel depending upon the specific application.

Since I did not mark `Final` as a stable state, I had added the corresponding explanation for it.
