### ISSUE TITLE
Test perun node on Ropsten testnet.

### ISSUE THREAD

**Issue by manoranjith** [hyperledger-labs/perun-node#130]
#### Motivation / Context

To ensure the node works with ropsten testnet.

#### Description

- [x] Create two accounts, one each for alice and bob; fund them with a few ethers by requesting it from the faucet.
- [x] Deploy the contracts using the `chain` command of `perunnode-cli`.
- [x] Start the `perunnode` with the address of the ethclient that is connected to testnet and the addresses of the deployed contracts.
- [x] Open a channel, send money on it, close it and close the session without force option.
- [x] Open a channel, send money on it and force close the session so that channel is persisted. Restart the session, send money on the restored channel, close it and close the session.
- [x] Write a script to automate this sequence. For reference, see [api/grpc/server_integ_test.go](https://github.com/hyperledger-labs/perun-node/blob/develop/api/grpc/server_integ_test.go) 

##### Relates to

Should be done after [Issue 417](https://git.perun.network/perun/go-perun/-/issues/417) in go-perun is completed. That relates using EIP155 compliant signatures in the `backend/ethereum/wallet` package of go-perun.

#### Testing

The scripted test should work without any failures on the Ropsten testnet.

#### Thread Safety

-NA-

**Comment by manoranjith** [comment]
On Ropsten (only PoW) testnet for ethereum,
1. funded the following 2 accounts from faucet: `0x6b53618f2d0a0f0e8a427550892ec4780dc0a667` (alice on-chain account) and `0x79CeEBB863Dbc013Fd6D1B4553c18FD062b9E950` (bob on-chain account).

2. Deployed adjudicator ([`0x7dd2c7d72aAADaE2467b429920d2df88798CCda4`](https://ropsten.etherscan.io/address/0x7dd2c7d72aAADaE2467b429920d2df88798CCda4)) and eth asset holder ([`0x30241b890b0c1A2d9B6Ce3D172020647C94E2AFa`](https://ropsten.etherscan.io/address/0x30241b890b0c1a2d9b6ce3d172020647c94e2afa)) contracts using alice on-chain account as the first two transactions on the testnet.

**Comment by ggwpez** [comment]
As mentioned in the internal chat; the contract code is now available for the ropsten deployment.  
[AssetHolder](https://ropsten.etherscan.io/address/0x30241b890b0c1A2d9B6Ce3D172020647C94E2AFa#code) and [Adjudicator](https://ropsten.etherscan.io/address/0x7dd2c7d72aAADaE2467b429920d2df88798CCda4#code) using go-perun version [27be1b2](https://github.com/perun-network/go-perun/tree/27be1b2016bd19bda0b7e9d0ec42ef5df4f903ac).

**Comment by manoranjith** [comment]
The contracts have been deployed on the Ropsten testnet, addresses of which can be found in the [above comment](https://github.com/hyperledger-labs/perun-node/issues/130#issuecomment-724647813). 

A complete sequences of state channel transaction was carried out successfully on the testnet and the logs can be found in the contract logs by clicking on the links mentioned in the above comment.

To try out the perun node on testnet, one can use existing keys or generate new ones and fund them from a faucet. The difference is only in step 2.

1. Clone the repo and `cd` into it.
2. Update account addresses. 
    a) To use existing accounts  updating the account address and keystore path in `alice/session.yaml` and `bob/session.yaml` files that will be generated after step 3.
    b) To generate new accounts, 
        1. Update the `RandSeedForTestAccs` variable in `ethereumtest/chain.go` to any random number of your choice.
        2. The account addresses can be found at `onchainaddr` in `alice/session.yaml` and `bob/session.yaml` files after running step 3, Request for these on testnet from the faucet and wait until these accounts are funded.
3. Run `make` to build the `perunnode` and `perunnode-cli` binaries.
4. In the generated artifacts, update the contracts addresses and blockchain node address in `node.yaml` file, `alice/session.yaml` and `bob/session.yaml` files.
The blockchain node address can any ethereum node connected to Ropsten testnet. Alternatively, an API service like Infura can also be used.

After this step, update the prepare the on-chain accounts as mentioned in step 2 and then tryout the two party payment channels using perun protocol using `perunnodecli`.

**Comment by manoranjith** [comment]
Script to run a test sequence can be run by modifying the contract addresses, on-chain accounts & keys in the `Test_Integ_Server` in `api/grpc` package.
