### ISSUE TITLE
Perun Network Identity Management

### ISSUE THREAD

**Issue by manoranjith** [hyperledger-labs/perun-node#43]
#### Motivation / Context

Define and implement a system that helps the user of the node to maintain a list of known off-chain participants that he can transact with in the off-chain network.

#### Description

The initial implementation of `perun-node` will use a static list of network participants provided by the user. This list contains a list of off-chain participants that user wants to transact with. Each participant will be referred using the term `Peer` and the list of `Peers` will be referred to as `Contacts`.

Each entry in the contacts (contact) will contain the following information about the peer:
1. Off-chain Address: Permanent identity of the peer in the off-chain network.
2. Communication Address: Address of the peer for off-chain communications.
3. Communication Type: Type of protocol supported by the peer for off-chain communication, for the given off-chain address.
4. Alias: A friendly name for the `Peer` chosen by the `User`. This name is chosen by the user and unique within a `Contacts` instance. This enables a user to reference this particular `Peer` when communicating with the `perun-node` via User API using friendly names rather than cryptographic addresses. This could be arbitrary name chosen by the user like `alice`, `bob` or name provided by ethereum naming service or anything else. 

How the `Contacts` will be used by the `perun-node`:

1. When user communicates with the node, he/she will be able to reference only those peers present in the `Contacts`. If a user wants to transact with a new peer, he/she should first add it to the `Contacts` via UserAPI and then reference it.
2. When node receives incoming connection requests,
  a. The connection will be automatically accepted if the `Peer` is present in the `Contacts`.
  b. The User will be presented with a notification to decided whether to `accept`/`decline` the connection if the `Peer` is not present in the `Contacts`. 
  If the user accepts the connection, he/she will also need to assign an `Alias`. The `Peer` will be added to the `Contacts` and connection will be accepted. Else the connection will be declined. 

The contacts should provide the following functionality.

1. A valid configuration file can be loaded without errors and cache the complete list.
2. Return an error when invalid configuration (syntax error or schema error) is provided.
3. Read entries from the contacts, references by `Alias` or by `Off-chain Address`. Dual index is required because the user API will use `Alias` for references while the `perun-core` will use `Off-chain Address` for references.
4. Write new entries to / Delete entries from the contacts. The read, write, delete operations should act only on the cache and not on the actual storage medium.
5. Update the latest state of cache to the underlying storage medium.

Also, a configuration file format to specify the list of known peers should be defined. Suggested language: YAML. 

##### Relates to

Relates to #39.

#### Testing

1. Tests should covered the described functionality.
 
#### Thread Safety

The configuration file will be loaded during Node initialization and hence this function will not be accessed concurrently.  Read, Write, Delete and UpdateStorage methods should be safe for concurrent user.

**Comment by manoranjith** [comment]
#### Hints for implementation

- [ ] Implement a new type `Contacts` in the `dst-go/identity` module.
  - [ ] It should store of map of `alias` of a peer to the `Peer` object. Use [`sync.Map`](https://golang.org/pkg/sync/#Map), so that it can be accessed by concurrent go-routines.
  - [ ] Implement the following methods over this type:
    - [ ] `Add(alias string, p Peer) (error) - Add a contact to this map. Use `map.Store()` internally. Error if the alias is already used in the map.
    - [ ] `Remove(alias string) (error)` - Remove a contact from this map. Use `map.Delete()` internally. Error if there is no entry for the given alias in the map.
    - [ ] `Get(alias string) (p Peer, isPresent bool)` - Get the details of a contact from this map. Use `map.Load()` internally. isPresent is false if no peer for the given alias in the list. It is true otherwise.  
  - Note: These wrapper types are required because methods over map use `interface{}` type for arguments, while the implemented methods will work with concrete types and do type assertions / conversions.

- Implement a new function `ContactsFromYaml(src io.Reader)(Contacts, error)` file.
  - Input to this function will be a reader containing data in yaml format. In practical scenarios, this will be file on disk.
  - The yaml file will have a  map of peer alias to peer struct.
  - Use the `[yaml.v2](https://godoc.org/gopkg.in/yaml.v2)` package to work with yaml data.
  - This function should return error, if it finds duplicate keys in the yaml file map.

**Comment by sebastianst** [comment]
I advise not to use `sync.Map`. It has a very special use case (see docs) which doesn't fit here. Better just create a struct that holds a map and a mutex.

**Comment by manoranjith** [comment]
In the docs, i read that `sync.Map` can be used instead of `map` + `sync.RWMutex` when 
1. entries are written once, but read many times (it is the case, because most entries are loaded initially from a file and later entries are added by the user at run time as well)
2. when multiple go-routines read entries (it is the case, because in each request user will reference a peer with its alias and the entry should be read from this map)

Regarding type safety, since `Add`, `Remove`, `Get` wrapper functions are used, type assertion or type assertion can be done there.

Is there something I am missing to see ?
@sebastianst
