### ISSUE TITLE
Command line app to run an instance of the perun node.

### ISSUE THREAD

**Issue by manoranjith** [hyperledger-labs/perun-node#98]
#### Motivation / Context

Implement a command line app that can be used to run an instance of the perun node.

#### Description

The app should provide the following commands and corresponding options:
1. `run`: Run an instance of the node. It should have following options:
  a. `--configFile`: path to the node config file.
  b. `--logLevel`:  log level for the node and all derived loggers. Default value: `node.log`.
  c.  `--logFile`: filepath to write logs. Empty string represents stdout. Default value: `info`.
  d. `--chainURL`: Address of the default blockchain node. Default value: `ws://127.0.0.1:8545`.
  e. `--adjudicator`: Address of the default Adjudicator contract.
  f. `--asset`: Address of the default Asset Holder contract.

If config file is provided, it is optional to specify the other parameters. The value of other parameters (if specified), will override the values specified in the config file.
If `--configFile` is not specified, it is mandatory to specify atleast  `--adjudicator` and `--asset`. Default values will be used for other parameters that are not specified. 

2. `generate`: Generate the demo artifacts for trying out the perun-node. It should have the following options:
a. `--type`: Type of the artifact to be generated. It can have take three values: `node`, `alice` and `bob`. These options are independent and more than one of them can be provided as a comma separated list (without a white space).
  *  `node` option will generate a node configuration file `node.yaml` in the current directory. It can be be passed to the `--configFile` option of the `run` command.
  * `alice` and `bob` options will create directories with names `alice` and `bob` respectively. Each of the directory will contain three demo artifacts `session.yaml`, `contacts.yaml` and `keystore` directory.
These artifacts can be used by the client api instance when connecting with the perun node by specifying the session config file as `./alice/session.yaml` and `./bob/session.yaml` for `alice` and  `bob` respectively.

3. `version`: Print the version of `perun-node` and `go-perun` sdk used.
4. `help`: Print a help message.

#### Testing

1. A client should be able to connect to the server, once it is started using `run` command.
2. The `generate` command should produce artifacts that resemble the ones used in integration tests.

#### Thread Safety

Not required, only one of the commands will be invoked by the user at a given point of time.

**Comment by choeppler** [comment]
I wonder whether the `--configFile` option is specific to the `run` command or more of a global app option?

Are the options of the `generate` command mutually exclusive? What about the following interface then: `generate --config=type` where `type` is `node`, `alice`, or `bob`?

**Comment by manoranjith** [comment]
@choeppler The `--configFile` option is specific to the `run` command.

The options of the `generate` command are mutually exclusive. Thanks for the suggestion, I have updated the description with a more simplified interface for `generate` command.

**Comment by choeppler** [comment]
@manoranjith, regarding the updated description of the `generate` command:
- if options are "mutually exclusive", I would expect that they cannot be used at the same time...
- `generate --type=alice` and `generate --type=bob` create three files? Would they be stored in the current working directory using some fixed names?
- does `generate --type=node` write the configfile to the standard output stream or to a file using a default path? I guess the former would be more flexible, also in terms of testability. But in terms of consistency of the interface, it should behave as the `generate` commands for alice and bob, I think.

**Comment by manoranjith** [comment]
Since the files will be created distinct fixed names, it should be safe to make the values for the `--type` option independent, so that they can be used simultaneously. 
Regarding writing to standard output stream or a file, I prefer the latter for consistency of interface (as you have also mentioned).

I have updated the above info and the details of what artifacts will be generated in the issue description.

**Comment by manoranjith** [comment]
@choeppler when implementing this, i see a constraint that both `alice` and `bob` config should be generated in one go. This is because, when creating the config, we query for two ports that are free and assign to alice and bob.
Since we need to add each other's details to the contacts file, it is need to know the config of one role when creating artifacts for the other role. Also, each of this config might not be useful by themselves, so it is both these can be created with a single option "session".

This will change `--type=node,alice,bob` to `--type=node,session`. But such an interface offers of possibility for the user to mispel the values and hence additional condition checks will be required. I think flags `--node, --session` could be a better interface. If they're misspelled, option not found error will be returned.

**Comment by choeppler** [comment]
Okay, I see. Actually, I now wonder what the benefit of those type-options is. How about always generating all of the required configs if none of them exists, yet, and returning an error message if they are already there? Then there would only be the need for one option, I guess: `--force | -f` to overwrite configs with the generated defaults.

**Comment by manoranjith** [comment]
Yes, it is possible to set "generate" if missing by default. 

However, since the node config is independent of session config, i think options to generate both of them should be independent.

Considering both the above points, the user should user --session=false or --node=false by to disable any of it. So i think the simpler and more intuitive interface is the not generate by default. `perunnode generate`  prints help message, using `--session` or `--node` flag generates the corresponding config.

Also, force reg force, is it not better to leave it to the user to delete it ? But this we can also implement as a third flag if required.

**Comment by choeppler** [comment]
Actually, if in the CLI grammar there is no object detailing what to generate but only flags, I'd go with generate everything by default. So, how about
```sh
perunnode generate                # generates sensible default configs for node and session
perunnode generate --only-session # generates only session configs for alice and bob
perunnode generate --only-node    # generates only node config
```
I'd probably refrain from overwriting pre-existing configs but error out and either have the user delete them as you suggest, or offer a `--force` option.

**Comment by manoranjith** [comment]
Yeah, i think it can be done this way as well. But one diff, I see is that:
1. In previous approach, `perunnode generate` would print the usage message. So by default, the command will never fail. It will only if he specifies `--node` when there is `node.yaml`, it will error. This behavior is explicit. 
2. But in this approach, if `perunnode generate`  fails, it could that any one of the config is there. I find this to be not very explicit. But it has the benefit that, in the first run, all config are generated without any option.

What are your thoughts on the explicitness of the behavior ?

**Comment by choeppler** [comment]
Well, for me it would be surprising if a command just returns a usage message. If the command fails, I'd expect both a non-zero exit code and an error message.

As for usage message, I'd expect that if invoked with the '-h' option or via an explicit help command. I guess you'd get that kind of behavior anyway, if you use [cobra](https://cobra.dev/) to build the CLI.

**Comment by manoranjith** [comment]
Okay, in the case we can do the way you suggested in your previous comment, without a force flag (so it is upto the user to delete it). Yes, I am using cobra and it does have the `help` or `-h` flag enabled by default.

**Comment by manoranjith** [comment]
I am doing this task in three PRs, each comprising one commit with the following changes:
- [ ] Move the `cmd/perunnode` package (that implements node API related functionalities) to `node`, so that the former package path can be used for the executable package implementing perunnode app. 
- [ ] Implement perunnode `run`, `vesion` and `help` command.
- [ ] Implement perunnode `generate` command.
